import Link from 'next/link';
import Head from 'next/head'
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

export default function Home({launches}) {
  
  console.log(launches);
  return (
    <>
      <Head>
        <title>SpaceX Lauch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>SpaceX Launch Programs</h1>
        <div className="cards">
      {launches.map((launch) => {
        return (
          <div id={launch.id} className="card">
            <div className='about'>
              <h2>{launch.mission_name}</h2>
              <p>
                {new Date(launch.launch_date_local).toLocaleDateString("en-US")}
              </p>
            </div>
            <div style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center"
            }}>
              <button><Link href={launch.links.video_link}>Stream Mission</Link></button>
            </div>
          </div>
        );
      })}
    </div>
      </main>
    </>
  );
}


export async function getStaticProps() {
  // creating new instance of apollo Client
  const client = new ApolloClient({
    uri: "https://api.spacex.land/graphql/",
    cache: new InMemoryCache(),
  });

  // fetching data from graphql endpoint
  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 10) {
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
          }
          rocket {
            rocket_name
          }
          launch_success
        }
      }
    `,
  });

  return {
    props: {
      launches: data.launchesPast,
    },
  };
}


